#!/usr/bin/expect

set timeout 60
set host "31.97.21.53"
set user "root"
set password "@Ahs221400#123"
set dir "hercules-assist-insight"

spawn ssh -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$password\r"
    }
    timeout {
        exit 1
    }
}

expect "#"

send "cd $dir\r"
expect "#"

send "git pull\r"
expect "#"

send "docker compose up -d --build\r"
expect "#"

send "exit\r"
expect eof
